apiVersion: v1
data:
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    - email: admin@kubeflow.org
      hash: $2y$12$ruoM7FqXrpVgaol44eRZW.4HWS8SAvg6KYVVSCIwKQPBmTpCm.EeO
      username: admin
      userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
    - email: s-ram-12345
      hash: $2b$12$08vefeuoBGqJyiS06jcubeDUORfO8g/klToQqV0WWXU0AwaJX6vba
      username: s-ram-12345
    - email: f-tejveer-12345
      hash: $2b$12$EzdYlLEPKofz2QCvLtSJEuiqtaro5B1qD6eHhAktWCdxpzDfD.2m6
      username: f-tejveer-12345
    - email: s-ajay-12345
      hash: $2b$12$TLASEgV.guvb28R3U/Nu2eNTP8L7KkSDW7ednaES9xqCA/QdSoD66
      username: s-ajay-12345
    - email: f-ravi-12345
      hash: $2b$12$iz8by2anFkoBRy47bSOY/.1DP1yARFgnSMaB1.cyyFEcq5O5/957O
      username: f-ravi-12345
    staticClients:
    - id: kubeflow-oidc-authservice
      redirectURIs: ["/login/oidc"]
      name: 'Dex Login Application'
      secret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"issuer: http://dex.auth.svc.cluster.local:5556/dex\nstorage:\n  type: kubernetes\n  config:\n    inCluster: true\nweb:\n  http: 0.0.0.0:5556\nlogger:\n  level: \"debug\"\n  format: text\noauth2:\n  skipApprovalScreen: true\nenablePasswordDB: true\nstaticPasswords:\n- email: admin@kubeflow.org\n  hash: $2y$12$ruoM7FqXrpVgaol44eRZW.4HWS8SAvg6KYVVSCIwKQPBmTpCm.EeO\n  username: admin\n  userID: 08a8684b-db88-4b73-90a9-3cd1661f5466\n- email: s-ram-12345\n  hash: $2b$12$08vefeuoBGqJyiS06jcubeDUORfO8g/klToQqV0WWXU0AwaJX6vba\n  username: s-ram-12345\n- email: f-tejveer-12345\n  hash: $2b$12$EzdYlLEPKofz2QCvLtSJEuiqtaro5B1qD6eHhAktWCdxpzDfD.2m6\n  username: f-tejveer-12345\n- email: s-ajay-12345\n  hash: $2b$12$TLASEgV.guvb28R3U/Nu2eNTP8L7KkSDW7ednaES9xqCA/QdSoD66\n  username: s-ajay-12345\nstaticClients:\n- id: kubeflow-oidc-authservice\n  redirectURIs: [\"/login/oidc\"]\n  name: 'Dex Login Application'\n  secret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-02-26T07:02:33Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{},"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}}},"manager":"kfctl","operation":"Update","time":"2024-02-26T07:02:33Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:kubectl.kubernetes.io/last-applied-configuration":{}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2024-02-28T09:26:32Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{"f:config.yaml":{}}},"manager":"kubectl-edit","operation":"Update","time":"2024-03-02T01:13:54Z"}],"name":"dex","namespace":"auth","resourceVersion":"48963908","uid":"3d13e439-7b96-48ee-99c4-69b001dbfe61"}}
  creationTimestamp: "2024-02-26T07:02:33Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
      f:metadata:
        f:annotations: {}
    manager: kfctl
    operation: Update
    time: "2024-02-26T07:02:33Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:config.yaml: {}
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2024-03-05T07:08:10Z"
  name: dex
  namespace: auth
  resourceVersion: "50215860"
  uid: 3d13e439-7b96-48ee-99c4-69b001dbfe61
